# Default values for kuberos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: ministryofjustice/cloud-platform-kuberos
  tag: "2.6.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  annotations: 
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/set-identifier: "kuberos-cp-test"
    cloud-platform.justice.gov.uk/ignore-external-dns-weight: "true"
  # It can be default(default ingress-controller) or modsec(ingress-controller has the modsec WAF enabled)  
  className: ""
  host: login.<test>.cloud-platform.service.justice.gov.uk
  tls:
    - secretName: kuberos-tls
      host:
        - login.<test>.cloud-platform.service.justice.gov.uk

resources:
  limits:
    cpu: 10m
    memory: 200Mi
  requests:
    cpu: 1m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}

# These values will be supplied by the OIDC provider.
oidc:
  issuerUrl: "https://justice-cloud-platform.eu.auth0.com/"
  clientId: "<client-id>"
  clientSecret: "<client-secret>"

# Cluster specific values, replace `address` with the external URL to the
# kubernetes API. If you leave `ca` empty, kuberos will use the current
# cluster's CA certificate. Alternativly, you can specify one by passing the
# base64-encoded apiserver CA certificate.
cluster:
  name: "<test>.cloud-platform.service.justice.gov.uk"
  address: "<cluster-address>"
  ca: ""