{{- if .Values.circleci.enabled -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
{{- end }}